### ISSUE TITLE
OP profile disappeared from StackApps - is this still active?

### ISSUE THREAD

**Issue by hack-r** [monzita/stackexchangepy#1]
Hi,

Before getting started with you API I wanted to make sure that it's still an active project. I noticed that the profile on StackApps seems to have been deleted or something.

Thanks!

**Comment by monzita** [comment]
Hey, hack-r.
The package is active, there was a problem and I have deleted my profile, 
but I will make a new one, if it's necessary.

If you find any issues, pls feel free to share them and I will fix them.

Best regards
~ monzita

**Comment by hack-r** [comment]
Great! Working with your wrapper now, thanks!
